# Generated by Django 3.2.4 on 2021-06-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_signup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
